#!/usr/bin/env zsh 

echo "Linking the following files..."
echo ".oh-my-zsh/"
ln -sf $HOME/.dotfiles/zsh/.oh-my-zsh $HOME/.oh-my-zsh

echo ".zshrc"
ln -sf $HOME/.dotfiles/zsh/.zshrc $HOME/.zshrc

echo ".zsh/"
ln -sf $HOME/.dotfiles/zsh/.zsh $HOME/.zsh

echo ".p10k.zsh"
ln -sf $HOME/.dotfiles/zsh/.p10k.zsh $HOME/.p10k.zsh

echo ".vimrc"
ln -sf $HOME/.dotfiles/vim/.vimrc $HOME/.vimrc

echo ".tmux.conf"
ln -sf $HOME/.dotfiles/tmux/.tmux.conf $HOME/.tmux.conf

echo "\nRunning the following files..."
echo "\n.zshrc"
source $HOME/.zshrc

echo "\n.tmux.conf"
tmux source $HOME/.tmux.conf
